version: '3'

env:
  JQ: docker run --rm -i ghcr.io/jqlang/jq:1.7

tasks:
  default:
    cmds:
      - task --list

  # mkdocs
  mkdocs:
    desc: MkDocs build
    cmds:
      - docker run --rm -it -v ${PWD}:/docs ghcr.io/squidfunk/mkdocs-material:9.6 build

  mkdocs:live:
    desc: MkDocs development server
    vars:
      PORT: '{{.p | default "8002"}}'
    cmds:
      - docker run --rm -it -p {{.PORT}}:8000 -v ${PWD}:/docs ghcr.io/squidfunk/mkdocs-material:9.6

  # nektos/act
  act:push:
    desc: Test release
    cmds:
      - act push {{.CLI_ARGS}}

  act:push:version:
    desc: Test release for specific version
    summary: |
      Example:

      task act:push:version pv="8.4.10"
    vars:
      PHP_VERSIONS: '{{ .pv | default "8.4.10"}}'
    cmds:
      - act push --input version={{.PHP_VERSIONS}}

  act:job:prepare:
    desc: Act test "prepare" job
    cmds:
      - act -j prepare {{.CLI_ARGS}}

  act:job:build:
    desc: Act test "build" job
    cmds:
      - act -j build {{.CLI_ARGS}}

  act:job:merge:
    desc: Act test "merge" job
    cmds:
      - act -j merge {{.CLI_ARGS}}

  # buildx bake
  bake:
    desc: Bake
    vars:
      PHP_VERSIONS: '{{ .pv | default "8.1.33,8.2.29,8.3.24,8.4.11"}}'
    cmds:
      - PHP_VERSIONS={{.PHP_VERSIONS}} docker buildx bake --set *.platform=linux/amd64

  bake:print:
    desc: Bake print options without building
    vars:
      PHP_VERSIONS: '{{ .pv | default "8.1.33,8.2.29,8.3.24,8.4.11"}}'
    cmds:
      - PHP_VERSIONS={{.PHP_VERSIONS}} docker buildx bake --print | $JQ
