name: Security Check

on:
  schedule:
    - cron: '30 4 * * *'
  workflow_dispatch:

jobs:
  scan:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        image:
          - ghcr.io/toshy/php:8.1-fpm-bookworm
          - ghcr.io/toshy/php:8.2-fpm-bookworm
          - ghcr.io/toshy/php:8.3-fpm-bookworm
          - ghcr.io/toshy/php:fpm-bookworm
          - ghcr.io/toshy/php:8.1-fpm-bookworm-ffmpeg
          - ghcr.io/toshy/php:8.2-fpm-bookworm-ffmpeg
          - ghcr.io/toshy/php:8.3-fpm-bookworm-ffmpeg
          - ghcr.io/toshy/php:fpm-bookworm-ffmpeg
          - ghcr.io/toshy/php:8.1-fpm-bookworm-otel
          - ghcr.io/toshy/php:8.2-fpm-bookworm-otel
          - ghcr.io/toshy/php:8.3-fpm-bookworm-otel
          - ghcr.io/toshy/php:fpm-bookworm-otel
    steps:
      - name: Scan for vulnerabilities
        uses: crazy-max/ghaction-container-scan@v3
        with:
          image: ${{ matrix.image }}
          severity_threshold: CRITICAL
          annotations: true
        env:
          TRIVY_TIMEOUT: 5m
          TRIVY_IGNORE_UNFIXED: true
